### ISSUE TITLE
Please clarify possible flags for the commands

### ISSUE THREAD

**Issue by julio73** [amtrack/sfdx-browserforce-plugin#269]
Some of the flags are unclear in the commands. For instance, `sfdx browserforce:plan --help` mentions:
-  `-f` for the definition file, which I think is more relevant for `sfdx browserforce:apply` command where a definition file should already exist.
- `-s` flag for the state file, what does the state file accomplish?
- and the single example has a `-o` flag, perhaps it's a typo.

**Comment by amtrack** [comment]
@julio73 Thanks for reporting! You're absolutely right!
It looks like at the moment only the `apply` command with the definition file flag (`-f`) is working as expected.

Somehow I didn't finish implementing the plan command and the logic for the state and plan files 👀
