### ISSUE TITLE
Cannot read property 'Id' of undefined error

### ISSUE THREAD

**Issue by prai01** [amtrack/sfdx-browserforce-plugin#294]
Hi there,

I am looking into this plugin to import password protected JKS cert into a scratch org. I could turn on the Identity Provider but failed to import the cert.

I get "Cannot read property 'Id' of undefined".  This is the config json.

Any input please?

{
"$schema": "https://raw.githubusercontent.com/amtrack/sfdx-browserforce-plugin/v1.2.0/src/plugins/schema.json",
"settings": {
"security": {
"certificateAndKeyManagement": {
"importFromKeystore": [
{
"filePath": "./data/config/certificates/google_cloud.jks",
"name": "google_cloud",
"password": "*****************"
}
]
}
}
}
}

**Comment by jwalke** [comment]
I was able to reproduce this issue. I've attached the .json file I used plus the dummy keystore I created. I followed [these steps](https://lekkimworld.com/2019/12/09/generate-a-java-keystore-jks-which-is-importable-in-salesforce/) to create the password protected keystore file. 

[config.zip](https://github.com/amtrack/sfdx-browserforce-plugin/files/5162583/config.zip)

**Comment by amtrack** [comment]
@prai01 @jwalke Thanks for reporting!
I've published a new version, please update and try again.

Note: You only need to specify the `name` property when you want to change the case of the certificate name.
By default Salesforce reads the name from the JKS file but unfortunately this is all lowercase.

**Comment by prai01** [comment]
Thanks @amtrack for the fix. It works like a charm. 

Any tips if its possible to read the filePath and password from outside the project to secure them?

**Comment by amtrack** [comment]
@prai01 Great to hear!
At the moment, I don't have any convenient solution to achieve this.
You could generate the JSON file temporary for now.

```console
export BF_CERT_PASSWORD="*****"
echo "{ \"settings\": { \"security\": { \"certificateAndKeyManagement\": { \"importFromKeystore\": [ { \"filePath\": \"./data/config/certificates/google_cloud.jks\", \"name\": \"google_cloud\", \"password\": \"${BF_CERT_PASSWORD}\" } ] } } } }" > /tmp/browserforce-config.json
sfdx browserforce:apply -f /tmp/browserforce-config.json ...
rm -f /tmp/browserforce-config.json
unset BF_CERT_PASSWORD
```

For the future I'm thinking about generally allowing the config to be specified without having to write any file, but I haven't started yet.

**Comment by prai01** [comment]
Thanks @amtrack for the workaround.
