### ISSUE TITLE
HVS Enablement

### ISSUE THREAD

**Issue by ozanbotanls** [amtrack/sfdx-browserforce-plugin#375]
Would it be possible to activate the HVS setting within this plugin? Currently, in a scratch org definition file, you can only define the license itself, however, the actual feature doesn't get enabled.

https://help.salesforce.com/articleView?id=hvs_considerations.htm&type=5
_"High Velocity Sales can be deployed in scratch orgs, but the settings for the feature can’t be updated through the scratch org definition file. Instead, configure settings directly in the High Velocity Sales app."_

Especially in a CI / CD flow that would be great!

**Comment by amtrack** [comment]
@ozanbotanls I haven't used High Velocity Sales yet but I'll have a look at this in the next few days.

**Comment by amtrack** [comment]
@ozanbotanls It looks like this is well supported in the Metadata API and doesn't require browser automation: 
[HighVelocitySalesSettings](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_highvelocitysalessettings.htm)

You can enable and configure this feature this directly when creating a scratch org using the `settings` property in `config/project-scratch-def.json`:

```json
{
  "orgName": "My High Velocity Sales Org",
  "edition": "Developer",
  "language": "en_US",
  "features": ["HighVelocitySales"],
  "settings": {
    "highVelocitySalesSettings": {
      "enableHighVelocitySalesSetup": true,
      "enableACAutoSendEmail": true
    }
  }
}
```

So you can use a mix of `feature` and `settings` on scratch org creation, or you can retrieve/deploy metadata for an existing (scratch) org where the license is available:

```console
sfdx force:source:retrieve -m "Settings:HighVelocitySales"
sfdx force:source:deploy -m "Settings:HighVelocitySales"
```

Just make sure that you're using API version `47.0` or later.

**Comment by ozanbotanls** [comment]
@amtrack The setting itself doesn't work in the scratch definition file, the link I sent above already pointing to that. It always gives "unexpected error" and never creates the scratch org. 

As for your suggestion, because the source:retrieve and deploy also uses MDAPI, the result is the same. 
`"An unexpected error occurred. Please include this ErrorId if you contact support: 226540269-1999205 (-1106494095)"`

It must be enabled manually over here anyway.
![Screen Shot 2021-01-18 at 9 05 25 PM](https://user-images.githubusercontent.com/57642636/104978895-ef6e8780-59d0-11eb-8e0b-6779014a1568.png)

**Comment by amtrack** [comment]
@ozanbotanls Hmm, it worked for me.
Please see my minimal working example: https://github.com/amtrack/mwe-hvs-enablement

![image](https://user-images.githubusercontent.com/789765/105003789-663c6c80-5a33-11eb-8305-dcb82347ca6b.png)

**Comment by ozanbotanls** [comment]
@amtrack Can you please try to push what you are retrieving from your DevHub to scratch in the next step and then navigate to Setup > High Velocity Settings in the scratch org. Please send me a screenshot of your observation. 
Thanks

**Comment by amtrack** [comment]
@ozanbotanls Well, that was kind of difficult to understand! 🙄 
Yes, you're right and yes, it looks like it is possible to add this to sfdx-browserforce-plugin.
Given the time I've already spent on this, I will also try to implement this in the next few days.

---

I assumed that just by making the setup page available (`enableHighVelocitySalesSetup`) using Metadata or Scratch Org Setting, this feature is enabled.

However to enable this feature, this toggle (see screenshot) has to be checked, respectively the `enableHighVelocitySales` in the has to be set to true. And trying to do so using Metadata API, will throw the error message you've posted.
![image](https://user-images.githubusercontent.com/789765/105632808-7ac69d80-5e55-11eb-9353-4ccf8c610e84.png)


In comparison, when someone clicks the **Set Up and Enable HVS** button, the feature will be enabled properly.
And later on you'll be able to use the Metadata API to configure this.

**Comment by ozanbotanls** [comment]
@amtrack Well, I know, so annoying!! But good news was that you made it. Will try asap
Cheers!
