### ISSUE TITLE
SF to SF Setting Not Activated

### ISSUE THREAD

**Issue by ozanbotanls** [amtrack/sfdx-browserforce-plugin#419]
Hey @amtrack

I've been using "SF to SF activation" when spinning up a new scratch in my CI/CD pipeline. It used to work well, but it started to fail. 

In the logs, it never complains: Always getting this success message:
```
[SalesforceToSalesforce] retrieving state... done
[SalesforceToSalesforce] changing 'enabled' to 'true'... done
```

However, when trying to push my code **which has a dependency on the PartnerNetworkRecordConnection object** (which is only available once you activate the SF to SF feature in the target org) it fails saying the object doesn't exist.

And when I go manually check if the feature gets activated in the org, it is not. Apparently something wrong happens behind the scenes. So wanted to raise this as you could debug and tackle maybe?

**Comment by ozanbotanls** [comment]
Could it be related to here?
https://github.com/amtrack/sfdx-browserforce-plugin/blob/master/src/plugins/salesforce-to-salesforce/index.ts#L46

As this feature in the setup is only available in Classic mode, on the layout there are 2 input save buttons (one at the header and one at the footer) Could it be failing due to this clash?

**Comment by amtrack** [comment]
@ozanbotanls I wasn't able to reproduce this.
The E2E tests are passing in CI and when running this locally, the feature got enabled in my scratch org and I can query the `PartnerNetworkRecordConnection` object (`SELECT Id FROM PartnerNetworkRecordConnection`) without any error.

I'm looking forward to your results from running it locally in headful mode as described in my comment above.

**Comment by ozanbotanls** [comment]
Hey @amtrack 

Thanks for looking into it. First things first: the aforementioned problem doesn't occur all the time but started to happen now more than it used to do.

Secondly, I tried with headful mode with a brand new scratch that I created. The browser automation opened up the SF to SF page and then was even able to select "enable" checkbox, then it closed up the page. I assumed it also "saved" the form. But when I manually went to check the feature after the automation is done, no it was not the case. The feature was still inactive.

So, I'm suspicious about "clicking on the save button". There might be some inconsistent situation around this.

**Comment by amtrack** [comment]
@ozanbotanls Unfortunately I still cannot reproduce this.
About the two save buttons, I checked the [docs](https://pptr.dev/#?product=Puppeteer&version=v8.0.0&show=api-pageclickselector-options) of Puppeteer:

> If there are multiple elements satisfying the selector, the first will be clicked.

If you have any more hints about how to reproduce this issue, please let me know.

**Comment by ozanbotanls** [comment]
@amtrack Thanks a lot for surfacing this!

My configuration file was holding both HVS and SF to SF enablement. For the first try, it only activates HVS and couldn't "save" the SF to SF. When I re-run it is activated. Thus, as a workaround for my use case, I'm always running the command twice and it solves

**Comment by amtrack** [comment]
@ozanbotanls I'm now able to reproduce this given your description of the combination of those two feature enablements.
