### ISSUE TITLE
Add/Update picklist values

### ISSUE THREAD

**Issue by aly76** [amtrack/sfdx-browserforce-plugin#432]
UPDATE 12/5/21

The picklist plugin currently supports deletion, activation/deactivation and 'find and replace'. It would be useful to be able to add and update picklist values, as there have been cases where the Metadata API fails to add/update values (e.g. ContractStatus) and the only workaround is browser automation or manual intervention.

---

We're trying to replace picklist values in the `ContractStatus` standard value set, but keep getting "no action necessary" as an output. Is there something we are missing? 

Plugin version: 2.5.6
SFDX CLI: 7.99.0
salesforcedx: 51.0.0
Chromium: 91.0.4469.0 (Developer Build) (x86_64)

**To replicate:**
``` 
$ sfdx browserforce:apply -f definition-file.json -u scratchorg
logging in... done
Applying definition file definition-file.json to org scratchorg
[Picklists] retrieving state... done
[Picklists] no action necessary
logging out... done
```
```
# definition-file.json
{
    "$schema": "https://raw.githubusercontent.com/amtrack/sfdx-browserforce-plugin/master/src/plugins/schema.json",
    "settings": {
      "picklists": {
        "picklistValues": [
          {
            "metadataType": "StandardValueSet",
            "metadataFullName": "ContractStatus",
            "value": "In Approval Process",
            "newValue": "Pre Creation"
          },
          {
            "metadataType": "StandardValueSet",
            "metadataFullName": "ContractStatus",
            "value": "Draft",
            "newValue": "Queued"
          },
          {
            "metadataType": "StandardValueSet",
            "metadataFullName": "ContractStatus",
            "value": "Activated",
            "absent": false
          }
        ]
      }
    }
}
```
l

**Comment by aly76** [comment]
After a bit more experimentation, looks like what the plugin supports is "Find and Replace", whereas we're after "New" or "Edit" functionality for picklist values.

**Comment by amtrack** [comment]
@aly76 I assume there are some benefits for choosing browser automation over Metadata API for **adding** Picklist Values.

Would you mind sharing them?

**Comment by azlam-abdulsalam** [comment]
We ran into a specific scenario, for ContractStatus on a scratch org, Updating Metadata values using metadata result in an Integrity error

**Comment by azlam-abdulsalam** [comment]
This is what we are testing out,  hope its in the right direction. 
https://github.com/dxatscale/sfdx-browserforce-plugin/pull/1
