### ISSUE TITLE
Issue contributing Opportunity Split enablement

### ISSUE THREAD

**Issue by twhitesides** [amtrack/sfdx-browserforce-plugin#508]
I have a use case where I would like to create Scratch Orgs with Opportunity Splits already enabled.  I have attempted to follow your instructions in CONTRIBUTING.md.  I seem to be having an issue when it comes to trying it out.  The suggested command:
` ./bin/run browserforce:apply -f src/plugins/opportunity-splits/enable.json`
results in:

> Could not find plugin named 'opportunitySplits' in definition: {"$schema":"../schema.json","settings":{"opportunitySplits":{"enabled":true}}}

I did the yarn command and followed your instructions carefully, so I'm not certain what could be missing.

**Comment by amtrack** [comment]
@twhitesides Good catch! Thanks for reporting!

The Contribution Guide was missing the step to build the plugin:

I've now update the docs: https://github.com/amtrack/sfdx-browserforce-plugin/pull/509

**Comment by twhitesides** [comment]
Thanks for your answer.  I am not sure if I am doing something wrong or if, due to this particular interface being quite outdated and a mix of Lightning and Classic, this one will work differently.  I have been trying for a few hours but it cannot find the selector.

**Comment by amtrack** [comment]
@twhitesides It seems to have worked for me. Did you manually enable `Setup > Opportunity Team Settings > Enable Team Selling` in your Scratch Org?
That was a prerequisite for me to make the Setup Page for Opportunity Splits available.

**Comment by twhitesides** [comment]
Thanks for checking.  I did have that enabled and was using debug to be certain it was getting to the same page.  Oddly enough I was able to get this working once through recording a faked set of mimicking tab and enter keys, but it only worked once on one org.  If you cared to share I would love to know how you got things working, I seem to be unable to do so.

**Comment by amtrack** [comment]
@twhitesides I've implemented the wizard without applying any further configuration or handling of errors: https://github.com/amtrack/sfdx-browserforce-plugin/pull/524
Feel free to take this as a kickstart.

**Comment by whitesidest** [comment]
Thank you so much for your effort, and apologies for the delay in reply.  This seems to work very well.  Is there anything that I could contribute to in order to help this get merged into core for more people to benefit from?

**Comment by amtrack** [comment]
@whitesidest I was assuming there might be some more settings needed to be implemented.
If you confirm that the enablement - as implemented - is already sufficient, then I'll finalize and merge the PR.

**Comment by whitesidest** [comment]
It works perfectly in tests I try.  I'm delighted with it.  Thank you again.
