### ISSUE TITLE
Add option to enable the "Knowledge User" checkbox on a user

### ISSUE THREAD

**Issue by RupertBarrow** [amtrack/sfdx-browserforce-plugin#548]

**Comment by amtrack** [comment]
Hi @RupertBarrow , could you please explain the background of your request?

Can't this be done via SOAP API or Anonymous Apex?
Or is there something I'm not aware of?

**Comment by JackVeromeev** [comment]
@amtrack I guess, yes, it's possible via soap API or developer script `update new User(Id , UserPermissionsKnowledgeUser);`

**Comment by amtrack** [comment]
@RupertBarrow Could you please check and confirm?
