### ISSUE TITLE
Ability to use different browser for execution

### ISSUE THREAD

**Issue by strotto** [amtrack/sfdx-browserforce-plugin#557]
Hi, would it be possible to add an environment variable to allow users to specify an existing browser to run instead of using Chromium which is packaged with puppeteer?
We have strict access controls on our enterprise laptops where only whitelisted applications can be run, and unfortunately Chromium isn't one of them. I am able to edit the code in browserforce.js to launch my existing Chrome install instead.

**Comment by amtrack** [comment]
Hi @strotto This is already possible and I'm using this approach already for a client.

It is difficult to find in the puppeteer docs. But this is a puppeteer native configuration and environment variable:
https://pptr.dev/faq/#q-chromium-gets-downloaded-on-every-npm-ci-run-how-can-i-cache-the-download

```console
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# install sfdx-browserforce-plugin e.g.
sfdx plugins:install sfdx-browserforce-plugin

export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# run the plugin
sfdx browserforce:apply -f path/to/config.json
...
```

**Comment by strotto** [comment]
Legend, worked like a charm
