### ISSUE TITLE
Can I list changesets (inbound or outbound) with Browserforce ?

### ISSUE THREAD

**Issue by RupertBarrow** [amtrack/sfdx-browserforce-plugin#569]
If this is possible, please could you suggest directions to writing a plugin for this ?

**Comment by amtrack** [comment]
@RupertBarrow I like the idea and I think there might be other people who would love that as well (maybe @Szandor72 wants this or already has a solution).
Out of stand I don't know any API which returns this info. So it might be a good use case for browser automation.

But honestly I would not recommend to implement this here.
A typical plugin for sfdx-browserforce-plugin

- checks or applies features and settings
- its implementation should be idempotent
- the output of the `plan/apply` command designed for this purpose and not customizable

I guess many of the sfdx-browerforce-plugin concepts are not needed/appropriate for your requirements.
I assume you want something like

```console
$ sf changesets list outbound -o mydevorg
featX
featY
$ sf changesets list inbound -o qasandbox
featX
featY
featZ
fix1
fix2
```

having also maybe a `--json flag`.

Sounds a lot like a separate sf plugin to me.
If you plan to start this I could share with you my lessons learned and what I might do differently nowadays.

**Comment by RupertBarrow** [comment]
OK thanks for your feedback.
I'll look into writing an SF/SFDX plugin for this.
cc @Szandor72

**Comment by RupertBarrow** [comment]
Trying it out now : thanks Copilot !

```
Write a CLI in Javascript to scrape a web page from Salesforce.
Improve this by accepting a authurl as a parameter, as a replacement for username and password authentication.
Improve this by using SFDX to authenticate and open the browser : SFDX should log in using the auth url.
Improve this by browsing the setup page for outgoing changesets, instead of a Salesforce record page.
```
