### ISSUE TITLE
Support for "LinkedIn Sales Navigator"

### ISSUE THREAD

**Issue by dinhphieu** [amtrack/sfdx-browserforce-plugin#611]
Hi,

Tried looking back and forth the Metadata API docs, scratch org settings and browserforce supported settings in the JSON schema but didn't find any traces of "LinkedIn Sales Navigator" anywhere

Seems like it has 2 types of packages, one "legacy" managed package and one native baked straight in SF by default, which got recently implemented I believe, and searching for keywords in how to enable it programmatically leads to nowhere. I'm talking about this:
![image](https://github.com/amtrack/sfdx-browserforce-plugin/assets/42538587/e20c630b-3858-40b4-a6a9-f3f84b7a59e1)

Seems like it needs to be enabled manually the same way as the Sales Engagement settings (https://github.com/amtrack/sfdx-browserforce-plugin/issues/375)

If anyone got any clues, please feel free to rescue me out 😭

**Comment by amtrack** [comment]
@dinhphieu I agree, from what I can see there is no Metadata for this setting.
I'll give it a try to implement this in browserforce.

**Comment by amtrack** [comment]
@dinhphieu did you already try what implemented?

**Comment by dinhphieu** [comment]
@amtrack sorry, I was off during Lunar New Year's. Just gave it a try and it worked well so far, thanks a bunch!
