### ISSUE TITLE
Could not find plugin named 'security' 

### ISSUE THREAD

**Issue by patrykacc** [amtrack/sfdx-browserforce-plugin#633]
Following issue started to happen for my CI in recent hours:

Error (1): Could not find plugin named 'security' in definition: {"$schema":"https://raw.githubusercontent.com/amtrack/sfdx-browserforce-plugin/main/src/plugins/schema.json","settings":{"security":{"certificateAndKeyManagement":{"certificates":[],"importFromKeystore":[{"name":"CertName","filePath":"./config/certificates/CertName.jks","password":"***"}]}}}}

**Comment by amtrack** [comment]
Thanks @patrykacc for reporting! I'll look into it next week.

**Comment by patrykacc** [comment]
I confirmed locally that switching back to 4.1.1 resolve the issue.
For others, if you are affected by same issue changing your installation command of plugin to include specific version should help:
`sf plugins install sfdx-browserforce-plugin@4.1.1`

**Comment by thvd** [comment]
@amtrack  Seems still to be broken: 

```
 sf browserforce apply -f config/xyzproxy/browserforce-template.json

```


Results into: 

```

logging in... done
Error (2): Nonexistent flag: -f
See more help with --help

logging out... done

```
